[manifest]
version = "1.0.0"
dump_lua = true
priority = 2

# Track defeated blinds
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
position = "after"
pattern = '''defeat(self, silent)'''
payload = '''
G.GAME.blinds_defeated_list = G.GAME.blinds_defeated_list or {}
local bkey = (G.GAME and G.GAME.blind and G.GAME.blind.config and G.GAME.blind.config.blind and G.GAME.blind.config.blind.key)
if bkey then G.GAME.blinds_defeated_list[bkey] = (G.GAME.blinds_defeated_list[bkey] or 0) + 1 end
'''
match_indent = true

# An Absence has no reward
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
position = "after"
pattern = '''if G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward[type] then _reward = nil end'''
payload = '''
if G.GAME.round_resets.blind_choices[type] == "bl_minty_absence" then 
    _reward = nil 
end
'''
match_indent = true