[manifest]
version = "1.0.0"
priority = 1

# Modify outcome of scoring a debuffed card
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
position = "after"
pattern = '''
card_eval_status_text(card, 'debuff')
'''
payload = '''
if next(SMODS.find_card("j_minty_finity_calico")) then
    context.minty_score_debuffed_card = true
    local othercard = context.other_card
    context.other_card = card
    for i,calico in ipairs(SMODS.find_card("j_minty_finity_calico")) do
        local eff = G.P_CENTERS.j_minty_finity_calico:calculate(calico, context)
        if eff and next(eff) then
            SMODS.calculate_effect(eff, card)
        end
    end
    context.other_card = othercard
    context.minty_score_debuffed_card = nil
end
'''
match_indent = true